print("Interesting")
print("Inter\esting")
print("Inter\"esting")
print("Inter\nesting")
phrase = "Hello World"
print(phrase.upper())
print(phrase.isupper())
print(phrase.upper().isupper())
print(len(phrase))
print(phrase[0])
print(phrase.index("H"))
print(phrase.replace("Hello", "Bye"))